word_list = [
    'andhra pradesh',
    'arunachal pradesh',
    'assam',
    'bihar',
    'chhattisgarh',
    'goa',
    'gujarat',
    'haryana',
    'himachal pradesh',
    'jharkhand',
    'karnataka',
    'kerala',
    'madhya pradesh',
    'maharashtra',
    'manipur',
    'meghalaya',
    'mizoram',
    'nagaland',
    'odisha',
    'punjab',
    'rajasthan',
    'sikkim',
    'tamil nadu',
    'telangana',
    'tripura',
    'uttar pradesh',
    'uttarakhand',
    'west bengal',
    'visakhapatnam',
    'mumbai',
    'delhi',
    'bengaluru',
    'hyderabad',
    'ahmedabad',
    'chennai',
    'kolkata',
    'pune',
    'jaipur',
    'lucknow',
    'kanpur',
    'nagpur',
    'indore',
    'bhopal',
    'patna',
    'vadodara',
    'ghaziabad',
    'ludhiana',
    'agra',
    'nashik',
    'faridabad',
    'meerut',
    'rajkot',
    'kalyan',
    'vasai',
    'varanasi',
    'srinagar',
    'dhanbad',
    'amritsar',
    'raipur',
    'allahabad',
    'ranchi',
    'coimbatore',
    'jodhpur',
    'guwahati',
    'chandigarh',
    'hubli',
    'mysuru',
    'tiruchirappalli',
    'bareilly',
    'aligarh',
    'moradabad',
    'jalandhar',
    'bhubaneswar',
    'salem',
    'warangal',
    'guntur',
    'thiruvananthapuram',
    'noida'
]
